In [1]:
import numpy as np

# 1. Create a two dimensional array.

matrix = np.arange(0,10).reshape(2,-1)

print(matrix)

# 2. Create another array from the created array,  in which the elements of each row are in reverse order.

reverse_row = np.flipud(matrix)

print(reverse_row)

# 3. Create another array from the created array, where columns and rows are in reverse order.

reverse_column = np.fliplr(matrix)

print(reverse_column)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 3 2 1 0]
 [9 8 7 6 5]]
